NotaBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: NotaBundle:Default:index }
    

nota:
    pattern:  /avancenota/
    defaults: { _controller: NotaBundle:Avance:avance }
