#------------------------------Rutas Reporteros---------------------------#
#----------------formulario para crear avance-------------------#
avance:
    pattern:  /reportero/crea-avance/
    defaults: { _controller: NotaBundle:Formulario:crear_avance }
#----------------tabla de avances-------------------#
tabla_avance:
    pattern:  /reportero/tabla-avances/
    defaults: { _controller: NotaBundle:Avance:avances_reportero }
#----------------switch de opcines  para el avance-------------------#    
tabla_avance_opciones:
    pattern:  /reportero/tabla-avances/{opcion}/
    defaults: { _controller: NotaBundle:Avance:opciones_tabla_avances }