

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

PlazaBundle:
    resource: "@PlazaBundle/Resources/config/routing.yml"
    prefix:   /

NotaBundle:
    resource: "@NotaBundle/Resources/config/routing.yml"
    prefix:   /

EstadisticaBundle:
    resource: "@EstadisticaBundle/Resources/config/routing.yml"
    prefix:   /

DiarioBundle:
    resource: "@DiarioBundle/Resources/config/routing.yml"
    prefix:   /

AdministradorBundle:
    resource: "@AdministradorBundle/Resources/config/routing.yml"
    prefix:   /
    
sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin




# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
