security: 
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext  
        
        Noticias\UsuarioBundle\Entity\Usuario:    { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers: 
      
        main:
            providers:  [in_memory, usuarios]
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        usuarios:
            entity: { class: Noticias\UsuarioBundle\Entity\Usuario, property: alias }

    firewalls:
        principal:
            pattern:        ^/
            provider:       main
            anonymous:      ~
            form_login: 
                login_path: /login
                check_path: /check
                default_target_path: /inicio

            logout:
                path: /logout
                target: /
            remember_me:
                key: test1234
                lifetime: 604800 # 604.800 = 3.600 * 24 * 7 = 1 semana
            security: true

    access_control:
  
         - { path: ^/login     , roles:  IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/registro  , roles:  IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/inicio    , roles:  ROLE_USER }
         - { path: ^/editor    , roles:  ROLE_EDITOR }
         - { path: ^/administracion    , roles:  ROLE_ADMIN }
         
         
