parameters:
#    administrador.example.class: Noticias\AdministradorBundle\Example

services:
#    administrador.example:
#        class: %administrador.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
