parameters:
#    diario.example.class: Noticias\DiarioBundle\Example

services:
#    diario.example:
#        class: %diario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
